{% set name = "pandera" %}
{% set version = "0.22.1" %}

package:
  name: pandera-suite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 091ebc353383ba642e5a20ee0df763ed2059ab99cb4b2ac3e83f482de8493645

build:
  number: 0

outputs:
  - name: pandera-base
    build:
      noarch: python
      script:
        - python -m pip install . --no-deps -vv

    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
      commands:
        - pip check

    requirements:
      host:
        - python {{ python_min }}
        - setuptools
        - pip
      run:
        - python >={{ python_min }}
        - multimethod <=1.10.0
        - numpy >=1.19.0
        - packaging >=20.0
        - pandas >=1.2.0
        - pydantic >=1.5.0
        - typeguard
        - typing_inspect >=0.6.0
        - wrapt

  - name: pandera
    build:
      noarch: python
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}

  - name: pandera-strategies
    build:
      noarch: python
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
        - pandera.strategies
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - hypothesis >=6.92.7

  - name: pandera-hypotheses
    build:
      noarch: python
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
        - pandera.api.hypotheses
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - scipy

  - name: pandera-io
    build:
      noarch: python
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
        - pandera.io
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - pyyaml >=5.1
        - black
        - frictionless <=4.40.8

  - name: pandera-polars
    build:
      noarch: python
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
        - pandera.typing.polars
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - polars >=0.20.0

  - name: pandera-pyspark
    build:
      noarch: python
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
        - pandera.accessors.pyspark_accessor
        - pandera.typing.pyspark
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - pyspark >=3.2.0

  - name: pandera-modin
    build:
      noarch: python
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
        - pandera.accessors.modin_accessor
        - pandera.typing.modin
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - modin

  - name: pandera-modin-ray
    build:
      noarch: python
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
        - pandera.accessors.modin_accessor
        - pandera.typing.modin
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - modin-ray

  - name: pandera-modin-dask
    build:
      noarch: python
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
        - pandera.accessors.modin_accessor
        - pandera.typing.modin
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - modin-dask

  - name: pandera-dask
    build:
      noarch: python
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
        - pandera.accessors.dask_accessor
        - pandera.typing.dask
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - dask
        - distributed

  - name: pandera-mypy
    build:
      noarch: python
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
        - pandera.mypy
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - mypy
        - pandas-stubs

  - name: pandera-fastapi
    build:
      noarch: python
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
        - pandera.typing.fastapi
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - fastapi

  - name: pandera-geopandas
    build:
      noarch: python
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - pandera
        - pandera.typing.geopandas
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - geopandas
        - shapely

about:
  home: https://github.com/pandera-dev/pandera
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The open source framework for precision data testing
  description: |
    A simple, zero-configuration Python library to help you build
    confidence in the quality of your dataframe-like containers through
    data validation and property-based testing.
  doc_url: https://pandera.readthedocs.io/en/latest/
  dev_url: https://github.com/unionai-oss/pandera

extra:
  feedstock-name: pandera
  recipe-maintainers:
    - cosmicBboy
    - fhoehle
